matfile = '/Users/turjo/Library/CloudStorage/OneDrive-UniversityofGeorgia/particle_aggregation/test_code/epsilon_daily.mat';

% If you know exact fields, pass them explicitly to avoid wrong auto-picks:
[t_days, eps_series] = load_epsilon_series(matfile, 0, ...
    'time_field','S.mtime', ...          % <-- change to the actual field
    'eps_field','S.epsilon_ml', ...      % <-- change to the actual field
    'unit','auto', ...                   % converts from dB/log10 if needed
    'resample_daily',true, ...
    'smooth_win',3);                     % small smoothing if you want

cfg = SimulationConfig( ...
    'epsilon_profile','observed', ...
    'epsilon_time',   t_days, ...
    'epsilon_series', eps_series, ...
    'epsilon_ref',    1e-6, ...
    'p_alpha',        0.4, ...           % stickiness–ε coupling (0 → off)
    'disagg_use_nonlinear', true);

sim = CoagulationSimulation(cfg);
res = sim.run();
sim.generateOutputs(true);